dist: trusty
language: cpp
compiler:
      - clang
sudo: required
env:
      global:
          - secure: "j4twFlxt3xl8Dv5yH5mTlljRdxa7ZlVBTRaEtY2KCEi2nqL79c5naPXwwvU1GX35gEGMXW2dM2h8WEm3Wfa2Sg5jE1Ujz49R2Aczi46qTVmKrhXUwdQYNH1U2CQ9VeoUky0RsPrB3i0wHuOXSG6NekyCwoVQ1+QhO9c61Ek+A7XDOIZ+vHvEZMqR5UsrCBqhMS8oKIrBTcMpXmOBh5bMUU1dLnEF2u27ks24TZJpSH0gqaptTD3nqkzh9T3nbHk/2PFSD0ZQkKNsmDyAP6Uh2NSBVyeeSNqPFBkzCPlB6BFS5kD7MWeoqqVWO8CfMoBHyCSSs/MegmfTVzjctqdGuPPsQbmRE4EuPKfeLI47QPthkoDtfzF4DNH03sVttFAAYc6/uFF114jIGrBHOIDLrnn/Rojv2FhHRFlwsDQxXaJBIdSXsHqWLUv/0Ze5G+IBWgkE198EMriqD/Jm8dw2V8MxX5QEWYoggrg7SWS1aMcuNtsN5S+pnx8ONtGPHWOYEHA5qLrChQpU8h7MemoOwknb4hGOQrp8dNJ/nVS4yXtxFpazRkKTikhk88LJby+uB2sgNI52Nyj8sU/35k+dRWOF1QpLz38ibhUbL4hyahzBSWAXmDyWAn5clhTYPkPmIJGqxBRm27a3hf/7iVjdIrG5woK5L6yK/lb5CBwhjWk="
           - VERBOSE=1
before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-


install:
      - sudo apt-get install -qq cmake libsndfile1-dev libasound2-dev libjack-dev portaudio19-dev libc++-dev
before_script:
        - mkdir -p build
script:
  - "cd $TRAVIS_BUILD_DIR/build && cmake .. && make"

addons:
  coverity_scan:
    project:
      name: "vlazzarini/AuLib"
      description: "Build submitted via Travis CI"
    notification_email: vlazzarini@nuim.ie
    build_command_prepend: "./configure; make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan

notifications:
      email:
          recipients:
              - vlazzarini@nuim.ie
