dist: trusty
language: cpp
compiler: clang
sudo: required
env:
       global:
                 - secure: "Zv3mLtv-ZLdss1qGSRF9mg"

#before_install:
#       - sudo apt-get update
       
install:
       - sudo apt-get install -qq cmake doxygen libsndfile1-dev libasound2-dev libjack-dev libportmidi-dev portaudio19-dev libc++-dev
      
before_script:
       - mkdir -p build

script:
       - "[ ${COVERITY_SCAN_BRANCH} == 1 ] || (cd $TRAVIS_BUILD_DIR/build && cmake .. -DCMAKE_VERBOSE_MAKEFILE=1 && make)"

addons:
      coverity_scan:
             project:
                  name: "vlazzarini/AuLib"
                  notification_email: vlazzarini@nuim.ie
             build_command_prepend: "cov-configure --comptype clang --compiler clang-3.5 --template && mkdir -p $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build && cmake .."
             build_command: "make -C $TRAVIS_BUILD_DIR/build"
             branch_pattern: coverity_scan

notifications:
      email:
          recipients:
              - vlazzarini@nuim.ie
