dist: trusty
language: cpp
compiler: clang
sudo: required
env:
       global:
                 - secure: "cwr1nyJ9WPPGEBzlDUJ5PY/Hkdb6Ut0ZOwH811gW+9evit0rzH8N2QuUn5j2KSotWteK5iBUNF1sxZQzOLItRbb47FXOToA8ajgN58xxeL8BEd/ZgjMBvlBWKsCseIJs7uizbaIayrrRfLFM1hkVj7RtTOApgMEURFyj5VnZix6dqZuD2D2ndxSiUAzuXYbGgnvx72aTYdACpzbNfTufe+ABeE27jBTxFbTcz6F96LQMEv6Dt4rNqbCrD6vtklINIdZVmdSRbbC6fvsxsPqDPE5bgLtsMTC8QXiMTbpYsb27ICtgDzGGI7jZTIzA0EHtgIX+3FBSkHP9nkVFdy/jm62Mf3U3JucEmDuOXjPRzP1pbDvOG67nOYGFijNZSlo5WH1Pcr2QTQ/+PDOdfuM9CRyHksipLJSKms4eio0VYegYgi/H/WECTTld7UxGLk8CAWaQdMrk2Nc7r0nLgO3NCTFEplVmGSSsN8WjMO0zjp8wT8qRHhgoOLhZNrzxOpF3j6JRVoXmXcw+ifF9fSlpcaFR09i1oL6QLEewapZRwyKyk7zNLFo0wmVcEGo21RQneFXHg06tUv436hgz9mPXEAfn8W2WJTXijad/CTH9DZbhwg+i43TQDfDhKIxN4t0w1SpC2i9WT+Wzq5FrSV1igqRatGFmpwIr4fEipHsB2HE="

#before_install:
#       - sudo apt-get update
       
install:
       - sudo apt-get install -qq cmake doxygen libsndfile1-dev libasound2-dev libjack-dev libportmidi-dev portaudio19-dev libc++-dev
      
before_script:
       - mkdir -p build

script:
       - "[ ${COVERITY_SCAN_BRANCH} == 1 ] || (cd $TRAVIS_BUILD_DIR/build && cmake .. -DCMAKE_VERBOSE_MAKEFILE=1 && make)"

addons:
      coverity_scan:
             project:
               name: "vlazzarini/aulib"
               notification_email: vlazzarini@nuim.ie
               build_command_prepend: "cov-configure --comptype clang --compiler clang-3.5 --template && mkdir -p $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build && cmake .."
               build_command: "make -C $TRAVIS_BUILD_DIR/build"
               branch_pattern: coverity_scan

notifications:
      email:
          recipients:
              - vlazzarini@nuim.ie
