.TH "AudioBase" 3 "Fri Dec 9 2016" "Version 0.0" "AuLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AudioBase
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AudioBase\&.h>\fP
.PP
Inherited by \fBOscil\fP, \fBPhasor\fP, \fBSoundIn\fP\fC [private]\fP, and \fBTableRead\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAudioBase\fP (uint32_t nchnls=def_nchnls, double sr=def_sr, double vsize=def_vsize)"
.br
.ti -1c
.RI "virtual \fB~AudioBase\fP ()"
.br
.ti -1c
.RI "double * \fBoutput\fP ()"
.br
.ti -1c
.RI "double \fBoutput\fP (uint32_t ndx)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Audio DSP base class 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AudioBase::AudioBase (uint32_t nchnls = \fCdef_nchnls\fP, double sr = \fCdef_sr\fP, double vsize = \fCdef_vsize\fP)\fC [inline]\fP"
\fBAudioBase\fP constructor 
.br

.br
nchnls - number of channels 
.br
sr - sampling rate 
.br
vsize - vector size (frames) 
.br

.SS "virtual AudioBase::~AudioBase ()\fC [inline]\fP, \fC [virtual]\fP"
\fBAudioBase\fP destructor 
.SH "Member Function Documentation"
.PP 
.SS "double* AudioBase::output ()\fC [inline]\fP"
Get the audio output vector 
.SS "double AudioBase::output (uint32_t ndx)\fC [inline]\fP"
Get a single sample at ndx off the output audio vector 

.SH "Author"
.PP 
Generated automatically by Doxygen for AuLib from the source code\&.
