.TH "FourierTable" 3 "Fri Dec 9 2016" "Version 0.0" "AuLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FourierTable
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FourierTable\&.h>\fP
.PP
Inherits \fBFuncTable\fP\&.
.PP
Inherited by \fBSawTable\fP, \fBSquareTable\fP, and \fBTriangleTable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFourierTable\fP (uint32_t harms, double *amps=NULL, double phase=0\&., uint32_t tsize=def_tsize)"
.br
.ti -1c
.RI "\fBFourierTable\fP (uint32_t harms, uint32_t type=SAW_TABLE, uint32_t tsize=def_tsize)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBcreate\fP (uint32_t harms, double *amps, double phase)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Function tables based on Fourier Series 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FourierTable::FourierTable (uint32_t harms, double * amps = \fCNULL\fP, double phase = \fC0\&.\fP, uint32_t tsize = \fCdef_tsize\fP)"
\fBFourierTable\fP constructor 
.br

.br
harms - number of harmonics 
.br
amps - array of harmonic amplitudes 
.br
phase - phase offset 
.br
tsize - table size 
.br

.SS "FourierTable::FourierTable (uint32_t harms, uint32_t type = \fCSAW_TABLE\fP, uint32_t tsize = \fCdef_tsize\fP)"
\fBFourierTable\fP constructor 
.br

.br
harms - number of harmonics 
.br
type - wave type 
.br
tsize - table size 
.br

.SH "Member Function Documentation"
.PP 
.SS "void FourierTable::create (uint32_t harms, double * amps, double phase)\fC [protected]\fP"
Create the table 

.SH "Author"
.PP 
Generated automatically by Doxygen for AuLib from the source code\&.
