.TH "Oscili" 3 "Fri Dec 9 2016" "Version 0.0" "AuLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Oscili
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Oscili\&.h>\fP
.PP
Inherits \fBOscil\fP\&.
.PP
Inherited by \fBSamplePlayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOscili\fP (double amp, double freq, double phase=\&.0, double *table=NULL, uint32_t tsize=def_tsize, double sr=def_sr, uint32_t vsize=def_vsize)"
.br
.ti -1c
.RI "virtual void \fBprocess\fP ()"
.br
.ti -1c
.RI "virtual void \fBprocess\fP (double amp)"
.br
.ti -1c
.RI "virtual void \fBprocess\fP (double amp, double freq)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Linear interpolation oscillator 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Oscili::Oscili (double amp, double freq, double phase = \fC\&.0\fP, double * table = \fCNULL\fP, uint32_t tsize = \fCdef_tsize\fP, double sr = \fCdef_sr\fP, uint32_t vsize = \fCdef_vsize\fP)\fC [inline]\fP"
\fBOscili\fP constructor 
.br

.br
amp - amplitude 
.br
freq - frequency in Hz 
.br
phase - init phase (0-1) 
.br
 table - function table 
.br
tsize - table size 
.br
sr - sampling rate 
.br
vsize - vector size 
.br

.SH "Member Function Documentation"
.PP 
.SS "void Oscili::process ()\fC [virtual]\fP"
Process one vector of audio 
.PP
Reimplemented from \fBOscil\fP\&.
.PP
Reimplemented in \fBSamplePlayer\fP\&.
.SS "virtual void Oscili::process (double amp)\fC [inline]\fP, \fC [virtual]\fP"
Process one vector of audio with amplitude amp 
.PP
Reimplemented from \fBOscil\fP\&.
.PP
Reimplemented in \fBSamplePlayer\fP\&.
.SS "virtual void Oscili::process (double amp, double freq)\fC [inline]\fP, \fC [virtual]\fP"
Process one vector of audio with amplitude amp and frequency freq 
.PP
Reimplemented from \fBOscil\fP\&.
.PP
Reimplemented in \fBSamplePlayer\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AuLib from the source code\&.
