.TH "SampleTable" 3 "Fri Dec 9 2016" "Version 0.0" "AuLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SampleTable
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SampleTable\&.h>\fP
.PP
Inherits \fBFuncTable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSampleTable\fP (const char *name, uint32_t chn=1)"
.br
.ti -1c
.RI "uint32_t \fBnchnls\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Sampled-sound table from a soundfile 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SampleTable::SampleTable (const char * name, uint32_t chn = \fC1\fP)"
\fBSampleTable\fP constructor 
.br

.br
name - filename 
.br
chn - channel to load (0 = all channels) 
.br

.SH "Member Function Documentation"
.PP 
.SS "uint32_t SampleTable::nchnls ()\fC [inline]\fP"
Get the number of channels 

.SH "Author"
.PP 
Generated automatically by Doxygen for AuLib from the source code\&.
