.TH "SquareTable" 3 "Fri Dec 9 2016" "Version 0.0" "AuLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SquareTable
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WaveTables\&.h>\fP
.PP
Inherits \fBFourierTable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSquareTable\fP (uint32_t harms, uint32_t tsize=def_tsize)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Square wave table 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SquareTable::SquareTable (uint32_t harms, uint32_t tsize = \fCdef_tsize\fP)\fC [inline]\fP"
\fBSquareTable\fP constructor 
.br

.br
harms - number of harmonics 
.br
tsize - table size 
.br


.SH "Author"
.PP 
Generated automatically by Doxygen for AuLib from the source code\&.
