.TH "TableRead" 3 "Fri Dec 9 2016" "Version 0.0" "AuLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TableRead
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TableRead\&.h>\fP
.PP
Inherits \fBAudioBase\fP\&.
.PP
Inherited by \fBTableReadi\fP, and \fBTableReadic\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTableRead\fP (double *table, double phase=0\&., bool norm=true, bool wrap=true, uint32_t tsize=def_tsize, uint32_t vsize=def_vsize)"
.br
.ti -1c
.RI "virtual void \fBprocess\fP (double *phs)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Table reader with truncated lookup 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TableRead::TableRead (double * table, double phase = \fC0\&.\fP, bool norm = \fCtrue\fP, bool wrap = \fCtrue\fP, uint32_t tsize = \fCdef_tsize\fP, uint32_t vsize = \fCdef_vsize\fP)\fC [inline]\fP"
\fBTableRead\fP constructor 
.br

.br
table - function table 
.br
phase - initial phase 
.br
norm - normalisation switch 
.br
wrap - wraparound switch 
.br
tsize - table size 
.br
vsize - vector size 
.br

.SH "Member Function Documentation"
.PP 
.SS "void TableRead::process (double * phs)\fC [virtual]\fP"
takes in a frame of phase values and lookups up the table values 
.PP
Reimplemented in \fBTableReadic\fP, and \fBTableReadi\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AuLib from the source code\&.
